#!/usr/bin/env python3
"""Compatibility entrypoint and API re-export for the IBC GUI."""

from __future__ import annotations

from ibc.compute import (
    C0,
    EPS0,
    ETA0,
    GHZ_TO_HZ,
    INCH_TO_M,
    MU0,
    InverseCandidate,
    LayerConfig,
    LoadedLayer,
    MaterialTable,
    UncertaintyConfig,
    ambient_wave_impedance,
    build_uncertainty_scales,
    cascade_abcd,
    cascade_input_impedance,
    compute_angle_metrics,
    compute_angle_metrics_many,
    compute_stack_impedance,
    compute_stack_impedance_many,
    interp_complex,
    interp_complex_many,
    is_nominal_scale,
    layer_properties,
    layer_properties_many,
    layer_wave_params,
    make_sweep,
    mix_anisotropic,
    mix_anisotropic_many,
    normalize_backing,
    normalize_wave_polarization,
    validate_sweep_coverage,
)
from ibc.io import (
    layer_config_from_dict,
    layer_config_to_dict,
    load_project_file,
    read_material_table,
    save_project_file,
    write_output,
)
from ibc.ui import (
    ABOUT_TEXT,
    APP_ACRONYM,
    APP_NAME,
    APP_TITLE,
    DARK_THEME,
    HEATMAP_METRIC_KEYS,
    HEATMAP_METRIC_OPTIONS,
    INVERSE_SCORE_MODE_OPTIONS,
    LIGHT_THEME,
    MPL_AVAILABLE,
    TK_AVAILABLE,
    UNCERTAINTY_VIEW_OPTIONS,
    ImpedanceGui,
    LayerDialog,
    main,
)

__all__ = [
    "ABOUT_TEXT",
    "APP_ACRONYM",
    "APP_NAME",
    "APP_TITLE",
    "C0",
    "DARK_THEME",
    "EPS0",
    "ETA0",
    "GHZ_TO_HZ",
    "HEATMAP_METRIC_KEYS",
    "HEATMAP_METRIC_OPTIONS",
    "INCH_TO_M",
    "INVERSE_SCORE_MODE_OPTIONS",
    "InverseCandidate",
    "ImpedanceGui",
    "LIGHT_THEME",
    "LayerConfig",
    "LayerDialog",
    "LoadedLayer",
    "MPL_AVAILABLE",
    "MU0",
    "MaterialTable",
    "TK_AVAILABLE",
    "UNCERTAINTY_VIEW_OPTIONS",
    "UncertaintyConfig",
    "ambient_wave_impedance",
    "build_uncertainty_scales",
    "cascade_abcd",
    "cascade_input_impedance",
    "compute_angle_metrics",
    "compute_angle_metrics_many",
    "compute_stack_impedance",
    "compute_stack_impedance_many",
    "interp_complex",
    "interp_complex_many",
    "is_nominal_scale",
    "layer_config_from_dict",
    "layer_config_to_dict",
    "layer_properties",
    "layer_properties_many",
    "layer_wave_params",
    "load_project_file",
    "main",
    "make_sweep",
    "mix_anisotropic",
    "mix_anisotropic_many",
    "normalize_backing",
    "normalize_wave_polarization",
    "read_material_table",
    "save_project_file",
    "validate_sweep_coverage",
    "write_output",
]


if __name__ == "__main__":
    main()
